---
# tasks file for post
- name: install pip3
  apt:
    name: python3-pip
    state: present
    update_cache: true

- name: install cython  # fix the bug with thriftpy installation
  pip:
    name: cython
    state: present
    version: 0.29.23
    executable: pip3

- name: install post dependencies
  pip:
    state: present
    requirements: /opt/reddit/post-py/requirements.txt
    executable: pip3

- name: add post_config
  template:
    src: post_config.j2
    dest: /opt/reddit/post-py/post_config
  notify: reload reddit-post

- name: add reddit-post.service
  template:
    src: reddit-post.service.j2
    dest: /etc/systemd/system/reddit-post.service
  notify: reload reddit-post

- name: enable and start reddit-post.service
  systemd:
    state: started
    name: reddit-post
    enabled: true
    daemon_reload: true
