---
- hosts: reddit
  become: true
  pre_tasks:
    - name: clone repo
      git:
        repo: https://github.com/express42/reddit.git
        dest: /opt/reddit
        version: microservices_for_mc
        force: true
  roles:
    - ui_comment
    - post
    - db
